# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
