# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0002_resource_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
