# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0005_auto_20170506_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
