# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0006_auto_20170506_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
    ]
